spring:
  redis:
    host: 127.0.0.1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/donation?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&user=root&password=liuhuipeng123
server:
  port: 8083